name: weekly-run

on:
  # schedule:
    # - cron: '*/5 * * * *'
    # - cron: '5 8 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install necessary libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python Script
        # env:
        #   URI: ${{ secrets.URI }}
        run: train.ipynb
